// ─────────────────────────────────────────────────────────────────────────────
// THE DOMAIN LAYER — the pure "rules of voting".
//
// This file knows nothing about HTTP, WebSockets, timers, or logging. It is just
// the data and the rules: what a vote is, what switching a vote means, and how a
// winner is decided. Keeping it pure makes it easy to read and easy to test.
// ─────────────────────────────────────────────────────────────────────────────

// How a tie (equal vote counts at the end) is resolved:
//   "declare-tie"     -> it's officially a draw, there is no winner.
//   "earliest-leader" -> break the tie in favour of whoever was ahead first.
export type TiePolicy = "declare-tie" | "earliest-leader";

// An election is either still accepting votes ("open") or finished ("closed").
export type ElectionStatus = "open" | "closed";

// One of the two things people vote for. `id` is used in the API and in the
// vote counts; `label` is just a human-friendly name for display.
export interface Item {
  id: string;
  label: string;
}

// The final outcome, produced once the election closes.
export interface ElectionResult {
  outcome: "win" | "tie"; // did someone win, or was it a draw?
  winnerId: string | null; // the winning item's id, or null when it's a tie
  counts: Record<string, number>; // final tally, e.g. { cats: 3, dogs: 1 }
}

// A plain, read-only picture of the election at one moment in time. This is what
// we send back over REST and push over WebSocket — it never exposes internal
// objects, only this simple shape.
export interface ElectionSnapshot {
  id: string;
  status: ElectionStatus;
  items: Item[];
  counts: Record<string, number>;
  totalVotes: number; // how many distinct users have voted
  endsAt: number; // when voting closes, as epoch milliseconds
  result: ElectionResult | null; // null until the election is closed
}

/**
 * A single election and all the rules for running it.
 *
 * Important design choice: every method that changes state is *synchronous*
 * (there is no `await` inside them). Node.js runs JavaScript on one thread, so a
 * synchronous method runs start-to-finish without another request sneaking in
 * halfway. That is what makes two near-simultaneous votes safe — see vote().
 */
export class Election {
  // ── Fixed facts about this election (never change after construction) ──
  readonly id: string; // unique id, generated by the service layer
  readonly items: [Item, Item]; // exactly two competitors
  readonly endsAt: number; // the moment voting auto-closes (epoch ms)
  private readonly tiePolicy: TiePolicy; // how to settle an equal result

  // ── Mutable state (changes as people vote and as the clock runs out) ──
  private status: ElectionStatus = "open"; // starts open, becomes closed once
  private counts: Record<string, number>; // running tally per item id

  // Remembers the CURRENT vote of each user, keyed by userId.
  // We need this so a user can *switch*: to move their vote we must know where
  // it was before. It also enforces "one active vote per user".
  private userVotes = new Map<string, string>(); // userId -> itemId

  // Used only by the "earliest-leader" tie rule. It records which item was most
  // recently ahead on its own. If the final scores are tied, this is the item
  // that got there first, so it wins the tie-break.
  private lastSoleLeaderId: string | null = null;

  // The final result. Stays null while the election is open; filled in on close.
  private result: ElectionResult | null = null;

  constructor(params: {
    id: string;
    items: [Item, Item];
    endsAt: number;
    tiePolicy: TiePolicy;
  }) {
    this.id = params.id;
    this.items = params.items;
    this.endsAt = params.endsAt;
    this.tiePolicy = params.tiePolicy;
    // Start both items at zero votes.
    this.counts = { [params.items[0].id]: 0, [params.items[1].id]: 0 };
  }

  /**
   * Record a user's vote, or switch it if they already voted for the other item.
   *
   * Returns `true` if something actually changed (so the caller knows it's worth
   * telling connected clients), and `false` if the vote was a no-op.
   *
   * Why this is safe under concurrent requests: everything below runs in one
   * uninterrupted synchronous block — read the user's previous vote, adjust the
   * counts, save the new vote. No other request can run in the middle, so two
   * quick votes from the same user simply happen one after the other. The result
   * is a clean "last vote wins" with no double-counting.
   */
  vote(userId: string, itemId: string): boolean {
    // Rule 1: you can't vote after voting has closed.
    if (this.status !== "open") {
      throw new ElectionError("VOTING_CLOSED", "Voting is closed for this election.");
    }
    // Rule 2: you can only vote for one of the two real items.
    if (!(itemId in this.counts)) {
      throw new ElectionError("UNKNOWN_ITEM", `No item '${itemId}' in this election.`);
    }

    const previous = this.userVotes.get(userId); // what did they vote before?

    // Voting again for the same item does nothing — makes the API idempotent.
    if (previous === itemId) return false;

    // If they had voted for the other item, take that vote back first.
    if (previous !== undefined) this.counts[previous] -= 1;

    // Add their vote to the chosen item and remember the new choice.
    this.counts[itemId] += 1;
    this.userVotes.set(userId, itemId);

    this.updateLeader(); // keep the tie-break tracker up to date
    return true; // state changed -> caller should broadcast
  }

  /**
   * Close voting and work out the result. Safe to call more than once: after the
   * first call it just returns the result it already computed (idempotent).
   */
  close(): ElectionResult {
    if (this.status === "closed") return this.result!;
    this.status = "closed";
    this.result = this.computeResult();
    return this.result;
  }

  /**
   * Build a plain snapshot object describing the election right now.
   * We copy `counts` (with `{ ...this.counts }`) so callers can't accidentally
   * change our internal tally by editing the object we handed back.
   */
  snapshot(): ElectionSnapshot {
    return {
      id: this.id,
      status: this.status,
      items: this.items,
      counts: { ...this.counts },
      totalVotes: this.userVotes.size, // number of unique voters
      endsAt: this.endsAt,
      result: this.result,
    };
  }

  // Small helper so other layers can ask "is this finished?" without reaching
  // into private fields.
  isClosed(): boolean {
    return this.status === "closed";
  }

  /**
   * Keep track of who is currently ahead on their own, for the earliest-leader
   * tie rule. Called after every vote.
   *
   * If one item is strictly ahead, remember it. If the counts are equal we do
   * NOT overwrite the memory — so it keeps pointing at whoever led just before
   * the scores levelled, i.e. the one who "got there first".
   */
  private updateLeader(): void {
    const [a, b] = this.items;
    const ca = this.counts[a.id];
    const cb = this.counts[b.id];
    if (ca > cb) this.lastSoleLeaderId = a.id;
    else if (cb > ca) this.lastSoleLeaderId = b.id;
    // counts equal -> keep the previous leader on record.
  }

  /**
   * Decide the winner from the final counts.
   *   - Higher count wins outright.
   *   - Equal counts -> apply the configured tie policy.
   */
  private computeResult(): ElectionResult {
    const [a, b] = this.items;
    const ca = this.counts[a.id];
    const cb = this.counts[b.id];
    const counts = { ...this.counts }; // snapshot copy for the result

    if (ca > cb) return { outcome: "win", winnerId: a.id, counts };
    if (cb > ca) return { outcome: "win", winnerId: b.id, counts };

    // From here the two counts are equal — it's a tie on the numbers.
    // "earliest-leader" breaks it using whoever led first (if anyone ever did).
    if (this.tiePolicy === "earliest-leader" && this.lastSoleLeaderId) {
      return { outcome: "win", winnerId: this.lastSoleLeaderId, counts };
    }
    // Otherwise (or if no one was ever ahead) it's an honest draw.
    return { outcome: "tie", winnerId: null, counts };
  }
}

/**
 * A custom error type for expected, "your request was invalid" situations, e.g.
 * voting after close or for an unknown item. The `code` is a short machine
 * string (like "VOTING_CLOSED") that the REST layer maps to an HTTP status. Using
 * a dedicated class lets the transport layer tell these apart from real bugs.
 */
export class ElectionError extends Error {
  constructor(public readonly code: string, message: string) {
    super(message);
    this.name = "ElectionError";
  }
}
